#! /bin/sh

PROD=$(cat packages/blog/private/_infos.json | grep prod | awk '{ print $2 }' | sed s/\"//g | sed s/,//g)
STAGING=$(cat packages/blog/private/_infos.json | grep staging | awk '{ print $2 }' | sed s/\"//g | sed s/,//g)

cd packages/contribution
git pull
git add .
git commit -m "Update text"
git push
cd -

meteor deploy $PROD
meteor deploy $STAGING
